# pylint: skip-file

# В этом модуле константы для тестов промпт конструктора
# текущая подборка расшифрованная, когда средство одно
decrypted_collection_one_product = {
    'Возраст': 32,
    'Задача': 'Разбираешь состав одного средства, особенно уделяя внимание '
              'следующим пунктам: основные компоненты, активные компоненты, '
              'Увлажняющие и ухаживающие компоненты, Консерванты и регуляторы pH, '
              'Запрещенные или нежелательные компоненты, Дополнительные свойства, '
              'Текстура, Плюсы средства, Минусы средства, Вывод',
    'Запрос': 'Кожа лица: Глубокое увлажнение и питание. Кожа лица стала '
              'обезвоженной и тусклой из-за воздействия внешних факторов (ветер, '
              'солнце, мороз), требует интенсивного увлажнения и питания.',
    'Итог': None,
    'Категория': 'Уход за кожей лица',
    'Лучший вариант': None,
    'Пол': 'женский',
    'Специалист': 'Ты профессиональный трихолог с медицинским образованием. Твоя '
                  'задача подобрать максимально подходящее средство для человека. '
                  'Данные человека будут даны.',
    'Средства': 'Средство_1 - PULANNA Bio-gold & Grape. Состав: Основные '
                'действующие компоненты: экстракт листьев винограда, гриба рейши, '
                'корня женьшеня, витамин Е, диоксид титана, мика, био-золото, '
                'гиалуроновая кислота. Полный состав: aqua, glycerin, gold, '
                'sodium hyalurone, propylene glycol, vitis vinifera leaf extract, '
                'ganoderma lucidum stem extract, ginseng (panax ginseng) root '
                'extract, tocopheryl acetate, mica, titanium dioxide carbomer, '
                'triethanolamine, methylparaben, propylparaben, parfum, '
                'hydroxycitronellal, geraniol, butylphenyl metylpropional, '
                'linalool, citronellol, imidazolidynyl urea.. Тип продукта: крем '
                'для лица. ',
    'Тип': 'Тип кожи лица: Нормальная. Сбалансированная, гладкая, без излишней '
           'сухости или жирности. Поры малозаметны, цвет лица ровный. Минимальные '
           'проблемы, хорошая упругость и эластичность. Тип кожи лица: Сухая. '
           'Недостаток влаги и/или липидов. Может быть стянутость, шелушение, '
           'тусклый цвет лица. Тонкая, чувствительная, склонна к раннему '
           'появлению морщин.',
    'Хеш': 'a4ece7b3cb7753cfa8d776f0bf751aa8d0ee38b2302c05ac93d4da0bd6c605eb'}

prompt_for_one_product = {
    'prompt': '\n'
              'Подборка осуществляется для человека, который имеет женский пол,\n'
              'возраст: 32 года/лет.\n'
              'Так же у человека следующие параметры: Тип кожи лица: Нормальная. '
              'Сбалансированная, гладкая, без излишней сухости или жирности. Поры '
              'малозаметны, цвет лица ровный. Минимальные проблемы, хорошая '
              'упругость и эластичность. Тип кожи лица: Сухая. Недостаток влаги '
              'и/или липидов. Может быть стянутость, шелушение, тусклый цвет '
              'лица. Тонкая, чувствительная, склонна к раннему появлению '
              'морщин..\n'
              'С помощью подбираемого средства человек хочет решить следующую '
              'проблему:\n'
              'Кожа лица: Глубокое увлажнение и питание. Кожа лица стала '
              'обезвоженной и тусклой из-за воздействия внешних факторов (ветер, '
              'солнце, мороз), требует интенсивного увлажнения и питания..\n'
              '\n'
              '\n'
              'Информация о средстве и его составе: Средство_1 - PULANNA Bio-gold '
              '& Grape. Состав: Основные действующие компоненты: экстракт листьев '
              'винограда, гриба рейши, корня женьшеня, витамин Е, диоксид титана, '
              'мика, био-золото, гиалуроновая кислота. Полный состав: aqua, '
              'glycerin, gold, sodium hyalurone, propylene glycol, vitis vinifera '
              'leaf extract, ganoderma lucidum stem extract, ginseng (panax '
              'ginseng) root extract, tocopheryl acetate, mica, titanium dioxide '
              'carbomer, triethanolamine, methylparaben, propylparaben, parfum, '
              'hydroxycitronellal, geraniol, butylphenyl metylpropional, '
              'linalool, citronellol, imidazolidynyl urea.. Тип продукта: крем '
              'для лица. .\n'
              'Учти всю вышепредставленную информацию и проведи детальный анализ '
              'состава.\n'
              '\n'
              '\n'
              'Ответ ты должен дать в следующем виде: Разбираешь состав одного '
              'средства, особенно уделяя внимание следующим пунктам: основные '
              'компоненты, активные компоненты, Увлажняющие и ухаживающие '
              'компоненты, Консерванты и регуляторы pH, Запрещенные или '
              'нежелательные компоненты, Дополнительные свойства, Текстура, Плюсы '
              'средства, Минусы средства, Вывод',
    'system_prompt': 'Ты профессиональный трихолог с медицинским образованием. '
                     'Твоя задача подобрать максимально подходящее средство для '
                     'человека. Данные человека будут даны.',
}

decrypted_collection_carcinogen_free = {'Возраст': 32,
                                        'Задача': 'Создаешь рейтинг средств по приоритету от наиболее подходящего до '
                                                  'наименее подходящего по твоему мнению. При составлении этого '
                                                  'рейтинга лучшим средством считай то, в составе которого вообще не '
                                                  'содержится никаких канцерогенов и которое наиболее подходит под '
                                                  'запрос пользователя. В "Итоговой рекомендации" укажи только одно '
                                                  'лучшее средство и развернутое пояснение почему.',
                                        'Запрос': 'Волосы: Увлажнение и питание. Необходимо восстановить водный '
                                                  'баланс волос и насытить их полезными веществами, так как '
                                                  'недостаток влаги делает волосы сухими, ломкими и тусклыми. Важно '
                                                  'обеспечить глубокое питание по всей длине, укрепить структуру и '
                                                  'защитить волосы от внешних воздействий, чтобы они оставались '
                                                  'мягкими, гладкими и здоровыми. Волосы: Для частого мытья. '
                                                  'Необходимо мягкое и бережное очищение волос и кожи головы, так как '
                                                  'частое мытье может привести к пересушиванию, потере естественного '
                                                  'баланса и защитного слоя. Важно подобрать средство с деликатной '
                                                  'формулой, которое будет поддерживать свежесть волос, увлажнять и '
                                                  'укреплять их, не утяжеляя и не пересушивая.',
                                        'Категория': 'Шампуни',
                                        'Количество средств': 3,
                                        'Пол': 'женский',
                                        'Путь': None,
                                        'Специалист': 'Ты профессиональный трихолог с медицинским образованием. Твоя '
                                                      'задача подобрать максимально подходящее средство для человека. '
                                                      'Данные человека будут даны.',
                                        'Средства': 'Средство_1 - OUSHEN Curl & shine shampoo. Состав: Aqua(water, '
                                                    'eau), sodium c14-16 olefin sulfonate, cocamidopropyl betaine, '
                                                    'sodium chloride, cocamide methyl mea, dimethicone, glycol '
                                                    'distearate, benzyl alcohol, parfum, sodium benzoate, '
                                                    'phenoxyethanol, glycerin, polyquaternium-7, guar '
                                                    'hydroxypropyltrimonium chloride, disodium edta, sodium methyl '
                                                    'cocoyl taurate, hydrogenated castor oil, lauric acid, citric '
                                                    'acid, trideceth-10, trideceth-3, simmondsia chinensis (jojoba) '
                                                    'seed oil, butyrospermum parkii (shea) butter, hydrolyzed '
                                                    'keratin, polyquaternium-11, ethylhexylglycerin, butylene glycol, '
                                                    'tocopherol.. Тип продукта: шампунь. \n'
                                                    'Средство_2 - NATURA SIBERICA Oblepikha. Состав: Aqua with '
                                                    'infusions of Novosieversia Glacialis ExtractWH (экстракт розы '
                                                    'арктической), Angelica Archangelica Root ExtractWH (экстракт '
                                                    'ангелики лекарственной), Rubus Chamaemorus Seed ExtractWH '
                                                    '(экстракт морошки сахалинской), Rosa Davurica Leaf ExtractWH '
                                                    '(экстракт шиповника даурского), Aralia Mandshurica Root Extract* '
                                                    '(экстракт аралии маньчжурской), Rosa Davurica Flower Water* '
                                                    '(гидролат розы даурской), Rhodiola Rosea Root Extract* (экстракт '
                                                    'родиолы розовой), Hippophae Rhamnoidesamidopropyl BetaineHR, '
                                                    'Pineamidopropyl BetainePS; Sodium Coco-Sulfate, Lauryl '
                                                    'Glucoside, Cocamidopropyl Betaine, Coco-Glucoside, Panthenol, '
                                                    'Guar Hydroxypropyltrimonium Chloride, Glycol Distearate, '
                                                    'Glyceryl Oleate, Sodium Chloride, Hydrolyzed Vegetable Protein '
                                                    '(растительный кератин), Argania Spinosa Kernel Oil* '
                                                    '(марокканское масло арганы), Hippophae Rhamnoides Fruit Oil* '
                                                    '(масло алтайской облепихи), Vaccinium Macrocarpon Seed Oil* '
                                                    '(масло семян клюквы), Hydrolyzed Wheat Protein (протеины '
                                                    'пшеницы), Lactic Acid (молочная кислота), Glycolic Acid '
                                                    '(гликолевая кислота), Benzyl Alcohol, Benzoic Acid, Sorbic Acid, '
                                                    'Glycerin, Citric Acid, Parfum. (*) – органические ингредиенты '
                                                    '(WH) – органические экстракты дикорастущих растений Сибири (PS) '
                                                    '– производное масла сибирского кедра (HR) – производное масла '
                                                    'алтайской облепихи. Тип продукта: шампунь. \n'
                                                    'Средство_3 - ALTEREGO ITALY Curego Hydraday. Состав: Aqua '
                                                    '(Water), Ammonium Lauryl Sulfate, Cocamidopropyl Betaine, '
                                                    'Erythritol, Lactic Acid, Polysorbate 20, Parfum (Fragrance), '
                                                    'Sodium Benzoate, Sodium Gluconate, Sodium Hydroxide, '
                                                    'Propanediol, Guar Hydroxypropyltrimonium Chloride, Hexyl '
                                                    'Cinnamal, Citric Acid, Geraniol, Linalool, Hydroxycitronellal, '
                                                    'Tartaric Acid, Oryza Sativa (Rice) Extract, Gluconic Acid, '
                                                    'Saccharomyces Ferment Lysate Filtrate, Sodium Chloride, '
                                                    'Potassium Sorbate, Vitis Vinifera Seed Oil (Vitis Vinifera '
                                                    '(Grape) Seed Oil), Glycerin, Sorbitol, Lecithin, Xanthan Gum.. '
                                                    'Тип продукта: шампунь. ',
                                        'Тип': 'Тип волос: Нормальные. Волосы не слишком жирные, не слишком сухие. '
                                               'Хорошо держат форму и имеют естественный блеск. Тип волос: Сухие. '
                                               'Волосы Могут выглядеть тусклыми и ломкими. Часто спутываются и теряют '
                                               'эластичность. Требуют увлажнения и питания.',
                                        'Хеш': '6fa98fcf493402f8874e2771f891b25e8e5abbd8f8b6c4555e014791f3581407'}

expected_prompt_for_best_prod_carcinogen = {'prompt': '\n'
                                                      'Подборка осуществляется для человека, который имеет женский пол,\n'
                                                      'возраст: 32 года/лет.\n'
                                                      'Так же у человека следующие параметры: Тип волос: Нормальные. '
                                                      'Волосы не слишком жирные, не слишком сухие. Хорошо держат форму и '
                                                      'имеют естественный блеск. Тип волос: Сухие. Волосы Могут выглядеть '
                                                      'тусклыми и ломкими. Часто спутываются и теряют эластичность. '
                                                      'Требуют увлажнения и питания..\n'
                                                      'С помощью подбираемого средства человек хочет решить следующую '
                                                      'проблему:\n'
                                                      'Волосы: Увлажнение и питание. Необходимо восстановить водный '
                                                      'баланс волос и насытить их полезными веществами, так как '
                                                      'недостаток влаги делает волосы сухими, ломкими и тусклыми. Важно '
                                                      'обеспечить глубокое питание по всей длине, укрепить структуру и '
                                                      'защитить волосы от внешних воздействий, чтобы они оставались '
                                                      'мягкими, гладкими и здоровыми. Волосы: Для частого мытья. '
                                                      'Необходимо мягкое и бережное очищение волос и кожи головы, так как '
                                                      'частое мытье может привести к пересушиванию, потере естественного '
                                                      'баланса и защитного слоя. Важно подобрать средство с деликатной '
                                                      'формулой, которое будет поддерживать свежесть волос, увлажнять и '
                                                      'укреплять их, не утяжеляя и не пересушивая..\n'
                                                      '\n'
                                                      '\n'
                                                      'Информация о средствах, их типе и составах: Средство_1 - OUSHEN '
                                                      'Curl & shine shampoo. Состав: Aqua(water, eau), sodium c14-16 '
                                                      'olefin sulfonate, cocamidopropyl betaine, sodium chloride, '
                                                      'cocamide methyl mea, dimethicone, glycol distearate, benzyl '
                                                      'alcohol, parfum, sodium benzoate, phenoxyethanol, glycerin, '
                                                      'polyquaternium-7, guar hydroxypropyltrimonium chloride, disodium '
                                                      'edta, sodium methyl cocoyl taurate, hydrogenated castor oil, '
                                                      'lauric acid, citric acid, trideceth-10, trideceth-3, simmondsia '
                                                      'chinensis (jojoba) seed oil, butyrospermum parkii (shea) butter, '
                                                      'hydrolyzed keratin, polyquaternium-11, ethylhexylglycerin, '
                                                      'butylene glycol, tocopherol.. Тип продукта: шампунь. \n'
                                                      'Средство_2 - NATURA SIBERICA Oblepikha. Состав: Aqua with '
                                                      'infusions of Novosieversia Glacialis ExtractWH (экстракт розы '
                                                      'арктической), Angelica Archangelica Root ExtractWH (экстракт '
                                                      'ангелики лекарственной), Rubus Chamaemorus Seed ExtractWH '
                                                      '(экстракт морошки сахалинской), Rosa Davurica Leaf ExtractWH '
                                                      '(экстракт шиповника даурского), Aralia Mandshurica Root Extract* '
                                                      '(экстракт аралии маньчжурской), Rosa Davurica Flower Water* '
                                                      '(гидролат розы даурской), Rhodiola Rosea Root Extract* (экстракт '
                                                      'родиолы розовой), Hippophae Rhamnoidesamidopropyl BetaineHR, '
                                                      'Pineamidopropyl BetainePS; Sodium Coco-Sulfate, Lauryl Glucoside, '
                                                      'Cocamidopropyl Betaine, Coco-Glucoside, Panthenol, Guar '
                                                      'Hydroxypropyltrimonium Chloride, Glycol Distearate, Glyceryl '
                                                      'Oleate, Sodium Chloride, Hydrolyzed Vegetable Protein '
                                                      '(растительный кератин), Argania Spinosa Kernel Oil* (марокканское '
                                                      'масло арганы), Hippophae Rhamnoides Fruit Oil* (масло алтайской '
                                                      'облепихи), Vaccinium Macrocarpon Seed Oil* (масло семян клюквы), '
                                                      'Hydrolyzed Wheat Protein (протеины пшеницы), Lactic Acid (молочная '
                                                      'кислота), Glycolic Acid (гликолевая кислота), Benzyl Alcohol, '
                                                      'Benzoic Acid, Sorbic Acid, Glycerin, Citric Acid, Parfum. (*) – '
                                                      'органические ингредиенты (WH) – органические экстракты '
                                                      'дикорастущих растений Сибири (PS) – производное масла сибирского '
                                                      'кедра (HR) – производное масла алтайской облепихи. Тип продукта: '
                                                      'шампунь. \n'
                                                      'Средство_3 - ALTEREGO ITALY Curego Hydraday. Состав: Aqua (Water), '
                                                      'Ammonium Lauryl Sulfate, Cocamidopropyl Betaine, Erythritol, '
                                                      'Lactic Acid, Polysorbate 20, Parfum (Fragrance), Sodium Benzoate, '
                                                      'Sodium Gluconate, Sodium Hydroxide, Propanediol, Guar '
                                                      'Hydroxypropyltrimonium Chloride, Hexyl Cinnamal, Citric Acid, '
                                                      'Geraniol, Linalool, Hydroxycitronellal, Tartaric Acid, Oryza '
                                                      'Sativa (Rice) Extract, Gluconic Acid, Saccharomyces Ferment Lysate '
                                                      'Filtrate, Sodium Chloride, Potassium Sorbate, Vitis Vinifera Seed '
                                                      'Oil (Vitis Vinifera (Grape) Seed Oil), Glycerin, Sorbitol, '
                                                      'Lecithin, Xanthan Gum.. Тип продукта: шампунь. .\n'
                                                      '\n'
                                                      'Учти всю вышепредставленную информацию и проведи анализ составов.\n'
                                                      'Если в составе есть канцерогены, то укажи их названия.\n'
                                                      '\n'
                                                      '\n'
                                                      'Ответ ты должен дать в следующем виде: Создаешь рейтинг средств по '
                                                      'приоритету от наиболее подходящего до наименее подходящего по '
                                                      'твоему мнению. При составлении этого рейтинга лучшим средством '
                                                      'считай то, в составе которого вообще не содержится никаких '
                                                      'канцерогенов и которое наиболее подходит под запрос пользователя. '
                                                      'В "Итоговой рекомендации" укажи только одно лучшее средство и '
                                                      'развернутое пояснение почему.',
                                            'system_prompt': 'Ты профессиональный трихолог с медицинским образованием. '
                                                             'Твоя задача подобрать максимально подходящее средство для '
                                                             'человека. Данные человека будут даны.'}

best_combination_decryped = {
    'Возраст': 32,
    'Задача': 'Берешь исходное средство и анализируешь его состав, затем берешь '
              'остальные средства и анализируешь их составы тоже. Затем, исходя '
              'из составов средств и потребностей пользователя, подбираешь '
              'наиболее эффективное средство к исходному, чтобы получилась '
              'идеальная подборка, которая наилучшим образом будет работать в '
              'паре.',
    'Запрос': 'Волосы: Увлажнение и питание. Необходимо восстановить водный '
              'баланс волос и насытить их полезными веществами, так как '
              'недостаток влаги делает волосы сухими, ломкими и тусклыми. Важно '
              'обеспечить глубокое питание по всей длине, укрепить структуру и '
              'защитить волосы от внешних воздействий, чтобы они оставались '
              'мягкими, гладкими и здоровыми. Волосы: Для частого мытья. '
              'Необходимо мягкое и бережное очищение волос и кожи головы, так как '
              'частое мытье может привести к пересушиванию, потере естественного '
              'баланса и защитного слоя. Важно подобрать средство с деликатной '
              'формулой, которое будет поддерживать свежесть волос, увлажнять и '
              'укреплять их, не утяжеляя и не пересушивая.',
    'Категория': 'Шампуни',
    'Количество средств': 4,
    'Пол': 'женский',
    'Путь': None,
    'Специалист': 'Ты профессиональный трихолог с медицинским образованием. Твоя '
                  'задача подобрать максимально подходящее средство для человека. '
                  'Данные человека будут даны.',
    'Средства': 'Исходное средство - R+CO Atlantis Moisturizing B5 Shampoo. '
                'Состав: Water (Aqua/Eau), Sodium Cocoyl Isethionate, Sodium '
                'Lauroyl Methyl Isethionate, Acrylates Copolymer, Lauryl '
                'Glucoside, Cocamidopropyl Betaine, Glyceryl Stearate SE, Sodium '
                'Methyl Oleoyl Taurate, Glycerin, Fragrance (Parfum), Benzyl '
                'Alcohol, Coconut Acid, Sodium Lauroyl Sarcosinate, '
                'Coco-Glucoside, Trehalose, Sodium Isethionate, Sodium Benzoate, '
                'Disodium Cocoamphodipropionate, Benzoic Acid, Trisodium '
                'Ethylenediamine Disuccinate, Sorbic Acid, Panthenol, Sodium '
                'Laurate, Oryza Sativa (Rice) Bran Oil, Passiflora Edulis Seed '
                'Oil, Euterpe Oleracea Fruit Oil, Butylene Glycol, Cocoyl '
                'Hydroxyethyl Imidazoline, Opuntia Ficus-Indica Fruit Extract, '
                'Urtica Dioica (Nettle) Extract, Phenoxyethanol, Tocopherol, '
                'Limonene, Hydroxycitronellal. Тип продукта: шампунь. \n'
                'Средство_1 - R+CO Television Perfect Hair Conditioner. Состав: '
                'Aqua/Water/Eau, Cetearyl Alcohol, Glycerin, Cetyl Esters, '
                'Butyrospermum Parkii (Shea) Butter, Behentrimonium Chloride, '
                'Juniperus Communis Fruit Extract, Calendula Officinalis Flower '
                'Extract, Orbignya Oleifera Seed Oil, Panthenol, '
                'Hydroxypropyltrimonium Hydrolyzed Corn Starch, Dimethicone, '
                'Dimethiconol, Butyl Methoxydibenzoylmethane, Ethylhexyl '
                'Methoxycinnamate, Ethylhexyl Salicylate, Ethylhexylglycerin, '
                'Disodium EDTA, BHT, Citric Acid, Phenoxyethanol, '
                'Parfum/Fragrance, Limonene. Тип продукта: бальзамы и '
                'кондиционеры. \n'
                'Средство_2 - R+CO Atlantis Moisturizing B5 Conditioner. Состав: '
                'Water (Aqua/Eau), Cetearyl Alcohol, Glycerin, C12-15 Alkyl '
                'Benzoate, Behentrimonium Chloride, Cetyl Esters, Betaine, '
                'Fragrance (Parfum), Cetrimonium Chloride, Olea Europaea (Olive) '
                'Fruit Oil, Benzyl Alcohol, Isopropyl Alcohol, Guar '
                'Hydroxypropyltrimonium Chloride, Oryza Sativa (Rice) Bran Oil, '
                'Passiflora Edulis Seed Oil, Euterpe Oleracea Fruit Oil, '
                'Tocopherol, Benzoic Acid, Panthenol, Sorbic Acid, Sodium '
                'Hydroxide, Citric Acid, Disodium EDTA, Limonene, '
                'Hydroxycitronellal, Alpha-Isomethyl Ionone. Тип продукта: '
                'бальзамы и кондиционеры. \n'
                'Средство_3 - R+CO TELEVISION Perfect Hair Masque. Состав: '
                'Aqua/Water/Eau, Cetearyl Alcohol, Glycerin, Astrocaryum Murumuru '
                'Seed Butter, Cetyl Esters, Dimethicone, Behentrimonium Chloride, '
                'Fragrance/Parfum, Stearamidopropyl Dimethylamine, Acacia '
                'Concinna Fruit Extract, Balanites Aegyptiaca Fruit Extract, '
                'Gypsophila Paniculata Root Extract, Tremella Fuciformis '
                '(Mushroom) Extract, Hydrogenated Ethylhexyl Olivate, Panthenol, '
                'Hydrogenated Olive Oil Unsaponifiables, Cetrimonium Chloride, '
                'Cetyl Hydroxyethylcellulose, Guar Hydroxypropyltrimonium '
                'Chloride, Dimethiconol, Amodimethicone, C11-15 Pareth-7, '
                'Laureth-9, Trideceth-12, Polyquaternium-7, Sericin, Butyl '
                'Methoxydibenzoylmethane, Ethylhexyl Methoxycinnamate, Ethylhexyl '
                'Salicylate, Citric Acid, BHT, Disodium EDTA, Phenoxyethanol, '
                'Ethylhexylglycerin, Tocopherol, Potassium Sorbate, Sodium '
                'Benzoate, Sorbic Acid, Limonene.. Тип продукта: маски для '
                'волос. ',
    'Тип': 'Тип волос: Нормальные. Волосы не слишком жирные, не слишком сухие. '
           'Хорошо держат форму и имеют естественный блеск. Тип волос: Сухие. '
           'Волосы Могут выглядеть тусклыми и ломкими. Часто спутываются и теряют '
           'эластичность. Требуют увлажнения и питания.',
    'Хеш': '6a161403f3463652963265593cd6faf0ce327b9ef49d0fc183ee340fbbe9dc39'}

best_combination_prompt = {
    'prompt': '\n'
              'Подборка осуществляется для человека, который имеет женский пол,\n'
              'возраст: 32 года/лет.\n'
              'Так же у человека следующие параметры: Тип волос: Нормальные. '
              'Волосы не слишком жирные, не слишком сухие. Хорошо держат форму и '
              'имеют естественный блеск. Тип волос: Сухие. Волосы Могут выглядеть '
              'тусклыми и ломкими. Часто спутываются и теряют эластичность. '
              'Требуют увлажнения и питания..\n'
              'С помощью подбираемого средства человек хочет решить следующую '
              'проблему:\n'
              'Волосы: Увлажнение и питание. Необходимо восстановить водный '
              'баланс волос и насытить их полезными веществами, так как '
              'недостаток влаги делает волосы сухими, ломкими и тусклыми. Важно '
              'обеспечить глубокое питание по всей длине, укрепить структуру и '
              'защитить волосы от внешних воздействий, чтобы они оставались '
              'мягкими, гладкими и здоровыми. Волосы: Для частого мытья. '
              'Необходимо мягкое и бережное очищение волос и кожи головы, так как '
              'частое мытье может привести к пересушиванию, потере естественного '
              'баланса и защитного слоя. Важно подобрать средство с деликатной '
              'формулой, которое будет поддерживать свежесть волос, увлажнять и '
              'укреплять их, не утяжеляя и не пересушивая..\n'
              '\n'
              '\n'
              'Информация об исходном средстве, к которому подбираем дополнение, '
              'и его состав,\n'
              'а так же информация о средствах, которые подбираем к исходному '
              'средству,\n'
              'и их составах представлены далее: Исходное средство - R+CO '
              'Atlantis Moisturizing B5 Shampoo. Состав: Water (Aqua/Eau), Sodium '
              'Cocoyl Isethionate, Sodium Lauroyl Methyl Isethionate, Acrylates '
              'Copolymer, Lauryl Glucoside, Cocamidopropyl Betaine, Glyceryl '
              'Stearate SE, Sodium Methyl Oleoyl Taurate, Glycerin, Fragrance '
              '(Parfum), Benzyl Alcohol, Coconut Acid, Sodium Lauroyl '
              'Sarcosinate, Coco-Glucoside, Trehalose, Sodium Isethionate, Sodium '
              'Benzoate, Disodium Cocoamphodipropionate, Benzoic Acid, Trisodium '
              'Ethylenediamine Disuccinate, Sorbic Acid, Panthenol, Sodium '
              'Laurate, Oryza Sativa (Rice) Bran Oil, Passiflora Edulis Seed Oil, '
              'Euterpe Oleracea Fruit Oil, Butylene Glycol, Cocoyl Hydroxyethyl '
              'Imidazoline, Opuntia Ficus-Indica Fruit Extract, Urtica Dioica '
              '(Nettle) Extract, Phenoxyethanol, Tocopherol, Limonene, '
              'Hydroxycitronellal. Тип продукта: шампунь. \n'
              'Средство_1 - R+CO Television Perfect Hair Conditioner. Состав: '
              'Aqua/Water/Eau, Cetearyl Alcohol, Glycerin, Cetyl Esters, '
              'Butyrospermum Parkii (Shea) Butter, Behentrimonium Chloride, '
              'Juniperus Communis Fruit Extract, Calendula Officinalis Flower '
              'Extract, Orbignya Oleifera Seed Oil, Panthenol, '
              'Hydroxypropyltrimonium Hydrolyzed Corn Starch, Dimethicone, '
              'Dimethiconol, Butyl Methoxydibenzoylmethane, Ethylhexyl '
              'Methoxycinnamate, Ethylhexyl Salicylate, Ethylhexylglycerin, '
              'Disodium EDTA, BHT, Citric Acid, Phenoxyethanol, Parfum/Fragrance, '
              'Limonene. Тип продукта: бальзамы и кондиционеры. \n'
              'Средство_2 - R+CO Atlantis Moisturizing B5 Conditioner. Состав: '
              'Water (Aqua/Eau), Cetearyl Alcohol, Glycerin, C12-15 Alkyl '
              'Benzoate, Behentrimonium Chloride, Cetyl Esters, Betaine, '
              'Fragrance (Parfum), Cetrimonium Chloride, Olea Europaea (Olive) '
              'Fruit Oil, Benzyl Alcohol, Isopropyl Alcohol, Guar '
              'Hydroxypropyltrimonium Chloride, Oryza Sativa (Rice) Bran Oil, '
              'Passiflora Edulis Seed Oil, Euterpe Oleracea Fruit Oil, '
              'Tocopherol, Benzoic Acid, Panthenol, Sorbic Acid, Sodium '
              'Hydroxide, Citric Acid, Disodium EDTA, Limonene, '
              'Hydroxycitronellal, Alpha-Isomethyl Ionone. Тип продукта: бальзамы '
              'и кондиционеры. \n'
              'Средство_3 - R+CO TELEVISION Perfect Hair Masque. Состав: '
              'Aqua/Water/Eau, Cetearyl Alcohol, Glycerin, Astrocaryum Murumuru '
              'Seed Butter, Cetyl Esters, Dimethicone, Behentrimonium Chloride, '
              'Fragrance/Parfum, Stearamidopropyl Dimethylamine, Acacia Concinna '
              'Fruit Extract, Balanites Aegyptiaca Fruit Extract, Gypsophila '
              'Paniculata Root Extract, Tremella Fuciformis (Mushroom) Extract, '
              'Hydrogenated Ethylhexyl Olivate, Panthenol, Hydrogenated Olive Oil '
              'Unsaponifiables, Cetrimonium Chloride, Cetyl '
              'Hydroxyethylcellulose, Guar Hydroxypropyltrimonium Chloride, '
              'Dimethiconol, Amodimethicone, C11-15 Pareth-7, Laureth-9, '
              'Trideceth-12, Polyquaternium-7, Sericin, Butyl '
              'Methoxydibenzoylmethane, Ethylhexyl Methoxycinnamate, Ethylhexyl '
              'Salicylate, Citric Acid, BHT, Disodium EDTA, Phenoxyethanol, '
              'Ethylhexylglycerin, Tocopherol, Potassium Sorbate, Sodium '
              'Benzoate, Sorbic Acid, Limonene.. Тип продукта: маски для волос. '
              '.\n'
              '\n'
              'Учти всю вышепредставленную информацию и подбери наиболее '
              'подходящее одно средство в дополнение к исходному. \n'
              '\n'
              '\n'
              'Ответ ты должен дать в следующем виде: Берешь исходное средство и '
              'анализируешь его состав, затем берешь остальные средства и '
              'анализируешь их составы тоже. Затем, исходя из составов средств и '
              'потребностей пользователя, подбираешь наиболее эффективное '
              'средство к исходному, чтобы получилась идеальная подборка, которая '
              'наилучшим образом будет работать в паре.',
    'system_prompt': 'Ты профессиональный трихолог с медицинским образованием. '
                     'Твоя задача подобрать максимально подходящее средство для '
                     'человека. Данные человека будут даны.'}

BEST_SET_DECRYPED = ('\nНабор_1:\n'
                     'Продукт: R+CO Dallas Biotin Thickening Shampoo. '
                     'Артикул: 24320200017. Тип продукта: шампунь. Состав: - '
                     'Биотин: улучшает кератиновую структуру волоса. Гарантирует '
                     'укрепление и придает силу волосяному стержню - Провитамин В5 '
                     'проникает в состав волоса, гарантирует глубокое увлажнение, '
                     'обволакивает поверхность волосяного стержня и придает естественный '
                     'блеск - Эстракт ягод карликовой пальмы придает объем и уплотняет '
                     'волосы - Экстракт мушмулы насыщен витаминами и питательными '
                     'веществами, способствует улучшению качества волос..Продукт: '
                     'R+CO TELEVISION Perfect Hair Masque. Артикул: 19760310342. '
                     'Тип продукта: маски для волос. Состав: Экстракт тремеллы '
                     'фукусовидной удерживает влагу в составе волоса, обладает '
                     'заживляющим и защитными свойствами; Масло кокоса способствует '
                     'укреплению волос, питает, придает волосам блеск и мягкость; '
                     'Масло муру-муру, насыщенное увлажняющими компонентами, '
                     'гарантирует глубокое увлажнение и кондиционирует волосы; '
                     'Масло пекуи формирует защитный слой вокруг волоса, '
                     'запечатывая влагу в его составе; Масло абиссинии '
                     'облегчает процесс расчесывания волос, придает блеск, '
                     'нейтрализует негативное воздействие окружающей среды; '
                     'Оливковое масло - увлажняет смягчает и кондиционирует '
                     'волосы, предотвращает спутывание. Высокая концентрация '
                     'витамина Е в составе защищает от негативного действия '
                     'свободных радикалов..'
                     '\nНабор_2:'
                     'Продукт: R+CO Atlantis'
                     ' Moisturizing B5 Shampoo. Артикул: 24320200015. '
                     'Тип продукта: шампунь. Состав: - провитамин В5, проникает в '
                     'волосы и обеспечивает глубокое увлажнение, обволакивает '
                     'волосяной стержень + придает волосам естественный блеск - '
                     'экстракт стволовых клеток опунции, содержит витамин Е, '
                     'богат минералами и антиоксидантами. Гарантирует '
                     'увлажнение волосам и коже головы, обеспечивает здоровый '
                     'уровень РН - масло рисовых отрубей (кондиционер) укрепляет '
                     'волосы, предотвращает появление секущихся концов, гарантирует '
                     'волосам питание, предотвращает появление фриззи-эффекта, '
                     'обеспечивает необходимые условия для здоровья волос и кожи головы.'
                     '.Продукт: R+CO Television Perfect Hair Conditioner. Артикул: 24320100036. '
                     'Тип продукта: бальзамы и кондиционеры. Состав: Содержит '
                     'экстракт ягод можжевельника и масло бабассу. В составе '
                     'отсутствуют парабены, сульфаты, минеральные масла и продукты '
                     'животного происхождения..'
                     )

best_set_prompt = {'prompt': '\n'
                             'Подборка осуществляется для человека, который имеет женский пол,\n'
                             'возраст: 32 года/лет.\n'
                             'Так же у человека следующие параметры: Тип волос: Нормальные. '
                             'Волосы не слишком жирные, не слишком сухие. Хорошо держат форму и '
                             'имеют естественный блеск. Тип волос: Сухие. Волосы Могут выглядеть '
                             'тусклыми и ломкими. Часто спутываются и теряют эластичность. '
                             'Требуют увлажнения и питания..\n'
                             'С помощью подбираемого средства человек хочет решить следующую '
                             'проблему:\n'
                             'Волосы: Увлажнение и питание. Необходимо восстановить водный '
                             'баланс волос и насытить их полезными веществами, так как '
                             'недостаток влаги делает волосы сухими, ломкими и тусклыми. Важно '
                             'обеспечить глубокое питание по всей длине, укрепить структуру и '
                             'защитить волосы от внешних воздействий, чтобы они оставались '
                             'мягкими, гладкими и здоровыми. Волосы: Для частого мытья. '
                             'Необходимо мягкое и бережное очищение волос и кожи головы, так как '
                             'частое мытье может привести к пересушиванию, потере естественного '
                             'баланса и защитного слоя. Важно подобрать средство с деликатной '
                             'формулой, которое будет поддерживать свежесть волос, увлажнять и '
                             'укреплять их, не утяжеляя и не пересушивая..\n'
                             '\n'
                             '\n'
                             'Информация о наборах средств:\n'
                             'Набор_1:\n'
                             'Продукт: R+CO Dallas Biotin Thickening Shampoo. Тип продукта: '
                             'шампунь. Состав: Water (Aqua/Eau), Sodium Lauroyl Sarcosinate, '
                             'Coco-Glucoside, Lauryl Glucoside, Cocamide MIPA, Sodium Cocoyl '
                             'Isethionate, Sodium Lauroyl Methyl Isethionate, Acrylates '
                             'Crosspolymer-4, Glycerin, Phenoxyethanol, Fragrance (Parfum), '
                             'Propanediol, Triheptanoin, Coco-Caprylate/Caprate, Coconut Acid, '
                             'Guar Hydroxypropyltrimonium Chloride, Potassium Sorbate, Caprylyl '
                             'Glycol, Sodium Isethionate, Polyquaternium-7, Panthenol, '
                             'Dilinoleic Acid/Butanediol Copolymer, Trisodium Ethylenediamine '
                             'Disuccinate, Oryza Sativa (Rice) Bran Extract, Tetrasodium '
                             'Glutamate Diacetate, Sodium Benzoate, Butylene Glycol, Helianthus '
                             'Annuus (Sunflower) Extract, Serenoa Serrulata Fruit Extract, '
                             'Cinnamidopropyltrimonium Chloride, Castor Oil/IPDI Copolymer, '
                             'Tocopherol, Rosmarinus Officinalis (Rosemary) Leaf Extract, '
                             'Hydrolyzed Quinoa, Biotin, Cocos Nucifera (Coconut) Oil, Brassica '
                             'Campestris/Aleurites Fordi Oil Copolymer, Eriobotrya Japonica Leaf '
                             'Extract, Litchi Chinensis Pericarp Extract, Benzyl Alcohol, '
                             'Hydrolyzed Vegetable Protein, Citric Acid, Disteareth-75 IPDI, '
                             'Sodium Hydroxide, Limonene. \n'
                             'Продукт: R+CO TELEVISION Perfect Hair Masque. Тип продукта: маски '
                             'для волос. Состав: Aqua/Water/Eau, Cetearyl Alcohol, Glycerin, '
                             'Astrocaryum Murumuru Seed Butter, Cetyl Esters, Dimethicone, '
                             'Behentrimonium Chloride, Fragrance/Parfum, Stearamidopropyl '
                             'Dimethylamine, Acacia Concinna Fruit Extract, Balanites Aegyptiaca '
                             'Fruit Extract, Gypsophila Paniculata Root Extract, Tremella '
                             'Fuciformis (Mushroom) Extract, Hydrogenated Ethylhexyl Olivate, '
                             'Panthenol, Hydrogenated Olive Oil Unsaponifiables, Cetrimonium '
                             'Chloride, Cetyl Hydroxyethylcellulose, Guar Hydroxypropyltrimonium '
                             'Chloride, Dimethiconol, Amodimethicone, C11-15 Pareth-7, '
                             'Laureth-9, Trideceth-12, Polyquaternium-7, Sericin, Butyl '
                             'Methoxydibenzoylmethane, Ethylhexyl Methoxycinnamate, Ethylhexyl '
                             'Salicylate, Citric Acid, BHT, Disodium EDTA, Phenoxyethanol, '
                             'Ethylhexylglycerin, Tocopherol, Potassium Sorbate, Sodium '
                             'Benzoate, Sorbic Acid, Limonene.. \n'
                             '\n'
                             'Набор_2:\n'
                             'Продукт: R+CO Atlantis Moisturizing B5 Shampoo. Тип продукта: '
                             'шампунь. Состав: Water (Aqua/Eau), Sodium Cocoyl Isethionate, '
                             'Sodium Lauroyl Methyl Isethionate, Acrylates Copolymer, Lauryl '
                             'Glucoside, Cocamidopropyl Betaine, Glyceryl Stearate SE, Sodium '
                             'Methyl Oleoyl Taurate, Glycerin, Fragrance (Parfum), Benzyl '
                             'Alcohol, Coconut Acid, Sodium Lauroyl Sarcosinate, Coco-Glucoside, '
                             'Trehalose, Sodium Isethionate, Sodium Benzoate, Disodium '
                             'Cocoamphodipropionate, Benzoic Acid, Trisodium Ethylenediamine '
                             'Disuccinate, Sorbic Acid, Panthenol, Sodium Laurate, Oryza Sativa '
                             '(Rice) Bran Oil, Passiflora Edulis Seed Oil, Euterpe Oleracea '
                             'Fruit Oil, Butylene Glycol, Cocoyl Hydroxyethyl Imidazoline, '
                             'Opuntia Ficus-Indica Fruit Extract, Urtica Dioica (Nettle) '
                             'Extract, Phenoxyethanol, Tocopherol, Limonene, '
                             'Hydroxycitronellal. \n'
                             'Продукт: R+CO Television Perfect Hair Conditioner. Тип продукта: '
                             'бальзамы и кондиционеры. Состав: Aqua/Water/Eau, Cetearyl Alcohol, '
                             'Glycerin, Cetyl Esters, Butyrospermum Parkii (Shea) Butter, '
                             'Behentrimonium Chloride, Juniperus Communis Fruit Extract, '
                             'Calendula Officinalis Flower Extract, Orbignya Oleifera Seed Oil, '
                             'Panthenol, Hydroxypropyltrimonium Hydrolyzed Corn Starch, '
                             'Dimethicone, Dimethiconol, Butyl Methoxydibenzoylmethane, '
                             'Ethylhexyl Methoxycinnamate, Ethylhexyl Salicylate, '
                             'Ethylhexylglycerin, Disodium EDTA, BHT, Citric Acid, '
                             'Phenoxyethanol, Parfum/Fragrance, Limonene. .\n'
                             'Учти всю вышепредставленную информацию и выдели лучший набор из '
                             'представленных. \n'
                             '\n'
                             '\n'
                             'Ответ ты должен дать в следующем виде: Подаются пары средств. Тебе '
                             'необходимо, основываясь на составах этих пар, определить какая из '
                             'предложенных пар в связке работает лучше всего и решает запросы '
                             'пользователя наиболее эффективно. Выделить эту пару и в выводе '
                             'написать обоснование почему именно это сочетание (эта пара) '
                             'лучшая.',
                   'system_prompt': 'Ты профессиональный трихолог с медицинским образованием. '
                                    'Твоя задача подобрать максимально подходящее средство для '
                                    'человека. Данные человека будут даны.'}

DECRYPT_BEST_PROD = ('Средство_1 - OUSHEN Curl & shine shampoo. Артикул: 19000220056. Состав: '
                     'Aqua(water, eau), sodium c14-16 olefin sulfonate, cocamidopropyl betaine, '
                     'sodium chloride, cocamide methyl mea, dimethicone, glycol distearate, benzyl '
                     'alcohol, parfum, sodium benzoate, phenoxyethanol, glycerin, '
                     'polyquaternium-7, guar hydroxypropyltrimonium chloride, disodium edta, '
                     'sodium methyl cocoyl taurate, hydrogenated castor oil, lauric acid, citric '
                     'acid, trideceth-10, trideceth-3, simmondsia chinensis (jojoba) seed oil, '
                     'butyrospermum parkii (shea) butter, hydrolyzed keratin, polyquaternium-11, '
                     'ethylhexylglycerin, butylene glycol, tocopherol.. Тип продукта: шампунь. \n'
                     'Средство_2 - NATURA SIBERICA Oblepikha. Артикул: 19000141580. Состав: Aqua '
                     'with infusions of Novosieversia Glacialis ExtractWH (экстракт розы '
                     'арктической), Angelica Archangelica Root ExtractWH (экстракт ангелики '
                     'лекарственной), Rubus Chamaemorus Seed ExtractWH (экстракт морошки '
                     'сахалинской), Rosa Davurica Leaf ExtractWH (экстракт шиповника даурского), '
                     'Aralia Mandshurica Root Extract* (экстракт аралии маньчжурской), Rosa '
                     'Davurica Flower Water* (гидролат розы даурской), Rhodiola Rosea Root '
                     'Extract* (экстракт родиолы розовой), Hippophae Rhamnoidesamidopropyl '
                     'BetaineHR, Pineamidopropyl BetainePS; Sodium Coco-Sulfate, Lauryl Glucoside, '
                     'Cocamidopropyl Betaine, Coco-Glucoside, Panthenol, Guar '
                     'Hydroxypropyltrimonium Chloride, Glycol Distearate, Glyceryl Oleate, Sodium '
                     'Chloride, Hydrolyzed Vegetable Protein (растительный кератин), Argania '
                     'Spinosa Kernel Oil* (марокканское масло арганы), Hippophae Rhamnoides Fruit '
                     'Oil* (масло алтайской облепихи), Vaccinium Macrocarpon Seed Oil* (масло '
                     'семян клюквы), Hydrolyzed Wheat Protein (протеины пшеницы), Lactic Acid '
                     '(молочная кислота), Glycolic Acid (гликолевая кислота), Benzyl Alcohol, '
                     'Benzoic Acid, Sorbic Acid, Glycerin, Citric Acid, Parfum. (*) – органические '
                     'ингредиенты (WH) – органические экстракты дикорастущих растений Сибири (PS) '
                     '– производное масла сибирского кедра (HR) – производное масла алтайской '
                     'облепихи. Тип продукта: шампунь. \n'
                     'Средство_3 - ALTEREGO ITALY Curego Hydraday. Артикул: 19000222487. Состав: '
                     'Aqua (Water), Ammonium Lauryl Sulfate, Cocamidopropyl Betaine, Erythritol, '
                     'Lactic Acid, Polysorbate 20, Parfum (Fragrance), Sodium Benzoate, Sodium '
                     'Gluconate, Sodium Hydroxide, Propanediol, Guar Hydroxypropyltrimonium '
                     'Chloride, Hexyl Cinnamal, Citric Acid, Geraniol, Linalool, '
                     'Hydroxycitronellal, Tartaric Acid, Oryza Sativa (Rice) Extract, Gluconic '
                     'Acid, Saccharomyces Ferment Lysate Filtrate, Sodium Chloride, Potassium '
                     'Sorbate, Vitis Vinifera Seed Oil (Vitis Vinifera (Grape) Seed Oil), '
                     'Glycerin, Sorbitol, Lecithin, Xanthan Gum.. Тип продукта: шампунь. ')

DECRYPT_BEST_ONE_PROD = ('Средство_1 - ALTEREGO ITALY Curego Hydraday. Артикул: 19000222487. Состав: '
                         'Aqua (Water), Ammonium Lauryl Sulfate, Cocamidopropyl Betaine, Erythritol, '
                         'Lactic Acid, Polysorbate 20, Parfum (Fragrance), Sodium Benzoate, Sodium '
                         'Gluconate, Sodium Hydroxide, Propanediol, Guar Hydroxypropyltrimonium '
                         'Chloride, Hexyl Cinnamal, Citric Acid, Geraniol, Linalool, '
                         'Hydroxycitronellal, Tartaric Acid, Oryza Sativa (Rice) Extract, Gluconic '
                         'Acid, Saccharomyces Ferment Lysate Filtrate, Sodium Chloride, Potassium '
                         'Sorbate, Vitis Vinifera Seed Oil (Vitis Vinifera (Grape) Seed Oil), '
                         'Glycerin, Sorbitol, Lecithin, Xanthan Gum.. Тип продукта: шампунь. ')
