
type_hair = "Волнистые, средней толщины, пористые, склонны к пушистости"
type_scalp = 'Нормальная'
features = 'Корни жирнеют быстро, длина и концы остаются сухими'

gender = 'женщина'
age = 32

sostav_1 = '''Oushen Curl & shine shampoo. Aqua(water, eau), sodium c14-16 olefin sulfonate, cocamidopropyl betaine, sodium chloride, cocamide methyl mea, dimethicone, glycol distearate, benzyl alcohol, parfum, sodium benzoate, phenoxyethanol, glycerin, polyquaternium-7, guar hydroxypropyltrimonium chloride, disodium edta, sodium methyl cocoyl taurate, hydrogenated castor oil, lauric acid, citric acid, trideceth-10, trideceth-3, simmondsia chinensis (jojoba) seed oil, butyrospermum parkii (shea) butter, hydrolyzed keratin, polyquaternium-11, ethylhexylglycerin, butylene glycol, tocopherol.'''
sostav_2 = '''ICE by NATURA SIBERICA REFRESH MY SCALP. Aqua, Sodium Coco-Sulfate, Coco-Glucoside, Sodium Chloride, Polyglyceryl- 10 Oleate, Decyl Glucoside, Mentha Arvensis Leaf Extract (Organic Wild Mint Extract), Laminaria Saccharina Extract WH (Organic Laminaria Extract), Eleutherococcus Senticosus Extract WH (Organic Siberian Ginseng Extract), Flavocetraria Nivalis Extract WH (Organic Snow Cladonia Extract), Dasiphora Fruticosa Extract (Organic Kuril Tea Extract), Salicylic Acid, Salvia Sclarea Oil (Organic Clary Sage Essential Oil), Melaleuca Alternifolia Leaf Oil (Organic Tea Tree Essential Oil), Guar Hydroxypropyltrimonium Chloride, Glyceryl Oleate, Allantoin, Menthyl Lactate, Taurine, Benzyl Alcohol, Sodium Benzoate, Potassium Sorbate, Citric Acid, Parfum, Linalool, Benzyl Salicylate. (WH) - Wild Harvested Siberian Plants Organic Extracts'''
sostav_3 = '''Natura Siberica Oblepikha. Aqua with infusions of Flavocetraria Nivalis ExtractWH (экстракт кладонии снежной), Sorbus Aucuparia Fruit ExtractWH (экстракт рябины сибирской), Macadamia Ternifolia Seed Oil (масло макадамии), Argania Spinosa Kernel Oil* (марокканское масло арганы), Pinus Pumila Needle ExtractWH (экстракт кедрового стланника), Pinus Sibirica Seed Oil* (масло кедрового ореха), Pulmonaria Officinalis Extract (медуница таежная), Aralia Mandshurica Root Extract* (экстракт аралии маньчжурской), Rosa Davurica Flower Water* (гидролат розы даурской), Rhodiola Rosea Root Extract* (экстракт родиолы розовой), Triticum Vulgare Germ Oil* (масло зародышей пшеницы), Hippophae Rhamnoides Fruit Oil* (масло алтайской облепихи), Hippophae Rhamnoidesamidopropyl BetaineHR, Pineamidopropyl BetainePS; Sodium Coco-Sulfate, Cocamidopropyl Betaine, Lauryl Glucoside, Coco-Glucoside, Glyceryl Oleate, Guar Hydroxypropyltrimonium Chloride, Hydrolyzed Vegetable Protein (растительный кератин), Panthenol (провитамин B5), Retinyl Palmitate (витамин А), Tocopheryl Acetate (Витамин E), Benzyl Alcohol, Sodium Chloride, Benzoic Acid, Sorbic Acid, Citric Acid, Parfum.
(*) – органические ингредиенты
(WH) – органические экстракты дикорастущих растений Сибири
(PS) – производное масла сибирского кедра
(HR) – производное масла алтайской облепихи '''
sostav_4 = '''ICE by NATURA SIBERICA TAME MY HAIR. Aqua, Sodium Coco-Sulfate, Coco-Glucoside, Sodium Chloride, Polyglyceryl-10 Oleate, Decyl Glucoside, Phospholipids, Sphingolipids (Ceramide Complex), Hydrolyzed Barley Protein (Plant Elastin), Pinus Sibirica Seed Oilwh (Organic Cedar Oil), Hippophae Rhamnoides Fruit Oil (Organic Seabuckthorn Pulp Oil), Helianthus Annuus Seed Oil (Organic Sunflower Oil), Rubus Chamaemorus Fruit Extract (Cloudberry Oily Extract), Linum Usitatissimum Seed Oil (Organic Linseed Oil), Amaranthus Spinosus Seed Oil (Organic Amaranth Oil), Rosa Canina Fruit Oil (Organic Rose Hip Oil), Corispermum Sibiricum Flower/Leaf/Stem Extract Wh, Rosa Davurica Leaf Extract Wh, Guar Hydroxypropyltrimonium Chloride, Glyceryl Oleate, Benzyl Alcohol, Sodium Benzoate, Potassium Sorbate, Citric Acid, Parfum, Benzyl Salicylate, Hexyl Cinnamal, Linalool, Geraniol. (WH) - Wild Harvested Siberian Plants Organic Extracts'''
sostav_5 = '''Weleda Millet Nourishing. Вода Двунатриевый кокоил глутамат Двунатриевый кокогликозид цитрат Аминокислоты овса Спирт Глицерин Ксантан, или ксантановая камедь Аромат Глицерил каприлат Пироглутамат натрия Экстракт семян проса Масло ореха макадамии Экстракт шалфея Лактоза, или молочный сахар Натрия кокоил глутамат Сахарозы лаурат Глицерил олеат Аргинин Фитат натрия Лимонен*1 Линалоол*1 Цитраль* Кумарин*
1 из концентрата натуральных масел.'''
sostav_6 = '''Weleda Oat Replenishing. Вода Двунатриевый кокоил глутамат Двунатриевый кокогликозид цитрат Аминокислоты овса Спирт Глицерин Ксантан, или ксантановая камедь Сахарозы лаурат Аромат Глицерил каприлат Пироглутамат натрия Экстракт зеленого овса Масло жожоба Экстракт шалфея Лактоза, или молочный сахар Натрия кокоил глутамат Глицерил олеат Аргинин Гидролизат протеинов пшеницы Фитат натрия Лимонен*1 Линалоол*1 Цитронеллол* Гераниол* Кумарин* 1 из концентрата натуральных масел'''


# строчка с потребностью - что именно хочет пользователь
features_or_problem = """
Я хочу решить проблему выпадения волос, так же шампунь должен быть с минимумом вредных компонентов
и подходить для частого использования.
"""