type_hair = "Волнистые, средней толщины, пористые, склонны к пушистости"
type_scalp = 'Нормальная'
features = 'Корни жирнеют быстро, длина и концы остаются сухими'

gender = 'женщина'
age = 32

sostav_1 = '''ICE by NATURA SIBERICA REFRESH MY SCALP. Aqua, Sodium Coco-Sulfate, Coco-Glucoside, Sodium Chloride, Polyglyceryl- 10 Oleate, Decyl Glucoside, Mentha Arvensis Leaf Extract (Organic Wild Mint Extract), Laminaria Saccharina Extract WH (Organic Laminaria Extract), Eleutherococcus Senticosus Extract WH (Organic Siberian Ginseng Extract), Flavocetraria Nivalis Extract WH (Organic Snow Cladonia Extract), Dasiphora Fruticosa Extract (Organic Kuril Tea Extract), Salicylic Acid, Salvia Sclarea Oil (Organic Clary Sage Essential Oil), Melaleuca Alternifolia Leaf Oil (Organic Tea Tree Essential Oil), Guar Hydroxypropyltrimonium Chloride, Glyceryl Oleate, Allantoin, Menthyl Lactate, Taurine, Benzyl Alcohol, Sodium Benzoate, Potassium Sorbate, Citric Acid, Parfum, Linalool, Benzyl Salicylate. (WH) - Wild Harvested Siberian Plants Organic Extracts'''
sostav_2 = '''Weleda Oat Replenishing. Вода Двунатриевый кокоил глутамат Двунатриевый кокогликозид цитрат Аминокислоты овса Спирт Глицерин Ксантан, или ксантановая камедь Сахарозы лаурат Аромат Глицерил каприлат Пироглутамат натрия Экстракт зеленого овса Масло жожоба Экстракт шалфея Лактоза, или молочный сахар Натрия кокоил глутамат Глицерил олеат Аргинин Гидролизат протеинов пшеницы Фитат натрия Лимонен*1 Линалоол*1 Цитронеллол* Гераниол* Кумарин* 1 из концентрата натуральных масел'''
sostav_3 = '''Lador KERATIN LPP SHAMPOO. Water, Cocamidopropyl Betaine, Disodium Laureth Sulfosuccinate, Lauramine Oxide, TEA-Cocoyl Glutamate, Glycerin, Butylene Glycol, Lauramide DEA, PEG-120 Methyl Glucose Dioleate, Sodium Benzoate, PEG-7 Glyceryl Cocoate, PPG-3 Caprylyl Ether, Citric Acid, Polyquaternium-10, Betaine, Hydroxypropyl Chitosan, Hydrolyzed Wheat Protein, Hydrolyzed Corn Protein, Hydrolyzed Soy Protein, Hydrolyzed Silk, Hydroxyacetophenone, Sodium Hyaluronate, Trehalose, Dipropylene Glycol, Zein, Argania Spinosa Kernel Oil, Persea Gratissima (Avocado) Oil, Camellia Japonica Seed Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Fragrance'''
sostav_4 = '''PAYOT Shampoing doux biome-friendly. Aqua (Water), Sodium Lauroyl Methyl Isethionate, Lauryl Glucoside, Cocamidopropyl Betaine, Sodium Methyl Cocoyl Taurate, Parfum (Fragrance), Pogostemon Cablin Leaf/Stem Extract, Salvia Officinalis Leaf Extract, Glycerin, Alpha-Glucan Oligosaccharide, Coco-Glucoside, Glyceryl Oleate, Tocopherol, Hydrogenated Palm Glycerides Citrate, Citric Acid, Polyquaternium-10, Phenethyl Alcohol, Chlorphenesin, Sodium Benzoate, Potassium Sorbate.'''
sostav_5 = '''Yves Rocher Volume Plumping Shampoo Sulfate Free. Aqua/water/eau • sodium cocoyl isethionate • sodium methyl cocoyl taurate • cocamidopropyl betaine • lauryl glucoside • chenopodium quinoa seed extract • fructooligosaccharides • inulin • sodium benzoate • parfum/fragrance • citric acid • panthenol • guar hydroxypropyltrimonium chloride • coco-glucoside • glyceryl oleate • potassium sorbate • sodium chloride • trisodium ethylenediamine disuccinate • tocopherol • lecithin • hydrogenated vegetable glycerides citrate'''
sostav_6 = '''Natura Siberica Oblepikha. Aqua with infusions of Flavocetraria Nivalis ExtractWH (экстракт кладонии снежной), Sorbus Aucuparia Fruit ExtractWH (экстракт рябины сибирской), Macadamia Ternifolia Seed Oil (масло макадамии), Argania Spinosa Kernel Oil* (марокканское масло арганы), Pinus Pumila Needle ExtractWH (экстракт кедрового стланника), Pinus Sibirica Seed Oil* (масло кедрового ореха), Pulmonaria Officinalis Extract (медуница таежная), Aralia Mandshurica Root Extract* (экстракт аралии маньчжурской), Rosa Davurica Flower Water* (гидролат розы даурской), Rhodiola Rosea Root Extract* (экстракт родиолы розовой), Triticum Vulgare Germ Oil* (масло зародышей пшеницы), Hippophae Rhamnoides Fruit Oil* (масло алтайской облепихи), Hippophae Rhamnoidesamidopropyl BetaineHR, Pineamidopropyl BetainePS; Sodium Coco-Sulfate, Cocamidopropyl Betaine, Lauryl Glucoside, Coco-Glucoside, Glyceryl Oleate, Guar Hydroxypropyltrimonium Chloride, Hydrolyzed Vegetable Protein (растительный кератин), Panthenol (провитамин B5), Retinyl Palmitate (витамин А), Tocopheryl Acetate (Витамин E), Benzyl Alcohol, Sodium Chloride, Benzoic Acid, Sorbic Acid, Citric Acid, Parfum.'''

# строчка с потребностью - что именно хочет пользователь
features_or_problem = """
Я хочу решить проблему выпадения волос, так же шампунь должен быть с минимумом вредных компонентов
и подходить для частого использования.
"""

all_cosmetics = {}
