type_hair = "Волнистые, средней толщины, пористые, склонны к пушистости"
type_scalp = 'Нормальная'
features = 'Корни жирнеют быстро, длина и концы остаются сухими'

gender = 'женщина'
age = 32

info_about_cosmetics = {
    "Oushen Curl & shine shampoo": '''Aqua(water, eau), sodium c14-16 olefin sulfonate, cocamidopropyl betaine, sodium chloride, cocamide methyl mea, dimethicone, glycol distearate, benzyl alcohol, parfum, sodium benzoate, phenoxyethanol, glycerin, polyquaternium-7, guar hydroxypropyltrimonium chloride, disodium edta, sodium methyl cocoyl taurate, hydrogenated castor oil, lauric acid, citric acid, trideceth-10, trideceth-3, simmondsia chinensis (jojoba) seed oil, butyrospermum parkii (shea) butter, hydrolyzed keratin, polyquaternium-11, ethylhexylglycerin, butylene glycol, tocopherol.''',
    "ICE by NATURA SIBERICA REFRESH MY SCALP": '''Aqua, Sodium Coco-Sulfate, Coco-Glucoside, Sodium Chloride, Polyglyceryl- 10 Oleate, Decyl Glucoside, Mentha Arvensis Leaf Extract (Organic Wild Mint Extract), Laminaria Saccharina Extract WH (Organic Laminaria Extract), Eleutherococcus Senticosus Extract WH (Organic Siberian Ginseng Extract), Flavocetraria Nivalis Extract WH (Organic Snow Cladonia Extract), Dasiphora Fruticosa Extract (Organic Kuril Tea Extract), Salicylic Acid, Salvia Sclarea Oil (Organic Clary Sage Essential Oil), Melaleuca Alternifolia Leaf Oil (Organic Tea Tree Essential Oil), Guar Hydroxypropyltrimonium Chloride, Glyceryl Oleate, Allantoin, Menthyl Lactate, Taurine, Benzyl Alcohol, Sodium Benzoate, Potassium Sorbate, Citric Acid, Parfum, Linalool, Benzyl Salicylate. (WH) - Wild Harvested Siberian Plants Organic Extracts''',
    "Natura Siberica Oblepikha": '''Aqua with infusions of Flavocetraria Nivalis ExtractWH (экстракт кладонии снежной), Sorbus Aucuparia Fruit ExtractWH (экстракт рябины сибирской), Macadamia Ternifolia Seed Oil (масло макадамии), Argania Spinosa Kernel Oil* (марокканское масло арганы), Pinus Pumila Needle ExtractWH (экстракт кедрового стланника), Pinus Sibirica Seed Oil* (масло кедрового ореха), Pulmonaria Officinalis Extract (медуница таежная), Aralia Mandshurica Root Extract* (экстракт аралии маньчжурской), Rosa Davurica Flower Water* (гидролат розы даурской), Rhodiola Rosea Root Extract* (экстракт родиолы розовой), Triticum Vulgare Germ Oil* (масло зародышей пшеницы), Hippophae Rhamnoides Fruit Oil* (масло алтайской облепихи), Hippophae Rhamnoidesamidopropyl BetaineHR, Pineamidopropyl BetainePS; Sodium Coco-Sulfate, Cocamidopropyl Betaine, Lauryl Glucoside, Coco-Glucoside, Glyceryl Oleate, Guar Hydroxypropyltrimonium Chloride, Hydrolyzed Vegetable Protein (растительный кератин), Panthenol (провитамин B5), Retinyl Palmitate (витамин А), Tocopheryl Acetate (Витамин E), Benzyl Alcohol, Sodium Chloride, Benzoic Acid, Sorbic Acid, Citric Acid, Parfum. 
(*) – органические ингредиенты, (WH) – органические экстракты дикорастущих растений Сибири, (PS) – производное масла сибирского кедра, (HR) – производное масла алтайской облепихи ''',
    "ICE by NATURA SIBERICA TAME MY HAIR": '''Aqua, Sodium Coco-Sulfate, Coco-Glucoside, Sodium Chloride, Polyglyceryl-10 Oleate, Decyl Glucoside, Phospholipids, Sphingolipids (Ceramide Complex), Hydrolyzed Barley Protein (Plant Elastin), Pinus Sibirica Seed Oilwh (Organic Cedar Oil), Hippophae Rhamnoides Fruit Oil (Organic Seabuckthorn Pulp Oil), Helianthus Annuus Seed Oil (Organic Sunflower Oil), Rubus Chamaemorus Fruit Extract (Cloudberry Oily Extract), Linum Usitatissimum Seed Oil (Organic Linseed Oil), Amaranthus Spinosus Seed Oil (Organic Amaranth Oil), Rosa Canina Fruit Oil (Organic Rose Hip Oil), Corispermum Sibiricum Flower/Leaf/Stem Extract Wh, Rosa Davurica Leaf Extract Wh, Guar Hydroxypropyltrimonium Chloride, Glyceryl Oleate, Benzyl Alcohol, Sodium Benzoate, Potassium Sorbate, Citric Acid, Parfum, Benzyl Salicylate, Hexyl Cinnamal, Linalool, Geraniol. (WH) - Wild Harvested Siberian Plants Organic Extracts''',
    "Weleda Millet Nourishing": '''Вода Двунатриевый кокоил глутамат Двунатриевый кокогликозид цитрат Аминокислоты овса Спирт Глицерин Ксантан, или ксантановая камедь Аромат Глицерил каприлат Пироглутамат натрия Экстракт семян проса Масло ореха макадамии Экстракт шалфея Лактоза, или молочный сахар Натрия кокоил глутамат Сахарозы лаурат Глицерил олеат Аргинин Фитат натрия Лимонен*1 Линалоол*1 Цитраль* Кумарин*1 из концентрата натуральных масел.''',
    "Weleda Oat Replenishing": '''Вода Двунатриевый кокоил глутамат Двунатриевый кокогликозид цитрат Аминокислоты овса Спирт Глицерин Ксантан, или ксантановая камедь Сахарозы лаурат Аромат Глицерил каприлат Пироглутамат натрия Экстракт зеленого овса Масло жожоба Экстракт шалфея Лактоза, или молочный сахар Натрия кокоил глутамат Глицерил олеат Аргинин Гидролизат протеинов пшеницы Фитат натрия Лимонен*1 Линалоол*1 Цитронеллол* Гераниол* Кумарин* 1 из концентрата натуральных масел''',
    "AlterEgo Italy Scalpego Balancing": '''Aqua (Water), Ammonium Lauryl Sulfate, Sodium Myreth Sulfate, Sodium Cocoamphoacetate, Sodium Chloride, Parfum (Fragrance), Lactic Acid, Sodium Benzoate, Guar Hydroxypropyltrimonium Chloride, Sodium Hydroxide, Propanediol, Citric Acid, Tartaric Acid, Avena Sativa Leaf/Stalk Extract (Avena Sativa Oat Leaf/Stalk Extract), Gluconic Acid, Saccharomyces Ferment Lysate Filtrate, Almond/Borage/Linseed/Olive Acids/Glycerides, Glycerin, Potassium Sorbate, Panthenol, Tocopherol, Salvia Officinalis Extract, Nasturtium Officinale Extract, Rosmarinus Officinalis Leaf Extract (Rosmarinus Officinalis (Rosemary) Leaf Extract), Niacin, Biotin. ''',
    "AlterEgo Italy Curego Hydraday": '''Aqua (Water), Ammonium Lauryl Sulfate, Cocamidopropyl Betaine, Erythritol, Lactic Acid, Polysorbate 20, Parfum (Fragrance), Sodium Benzoate, Sodium Gluconate, Sodium Hydroxide, Propanediol, Guar Hydroxypropyltrimonium Chloride, Hexyl Cinnamal, Citric Acid, Geraniol, Linalool, Hydroxycitronellal, Tartaric Acid, Oryza Sativa (Rice) Extract, Gluconic Acid, Saccharomyces Ferment Lysate Filtrate, Sodium Chloride, Potassium Sorbate, Vitis Vinifera Seed Oil (Vitis Vinifera (Grape) Seed Oil), Glycerin, Sorbitol, Lecithin, Xanthan Gum.''',
    "Lador KERATIN LPP SHAMPOO": '''Water, Cocamidopropyl Betaine, Disodium Laureth Sulfosuccinate, Lauramine Oxide, TEA-Cocoyl Glutamate, Glycerin, Butylene Glycol, Lauramide DEA, PEG-120 Methyl Glucose Dioleate, Sodium Benzoate, PEG-7 Glyceryl Cocoate, PPG-3 Caprylyl Ether, Citric Acid, Polyquaternium-10, Betaine, Hydroxypropyl Chitosan, Hydrolyzed Wheat Protein, Hydrolyzed Corn Protein, Hydrolyzed Soy Protein, Hydrolyzed Silk, Hydroxyacetophenone, Sodium Hyaluronate, Trehalose, Dipropylene Glycol, Zein, Argania Spinosa Kernel Oil, Persea Gratissima (Avocado) Oil, Camellia Japonica Seed Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Fragrance''',
    "PAYOT Shampoing doux biome-friendly": '''Aqua (Water), Sodium Lauroyl Methyl Isethionate, Lauryl Glucoside, Cocamidopropyl Betaine, Sodium Methyl Cocoyl Taurate, Parfum (Fragrance), Pogostemon Cablin Leaf/Stem Extract, Salvia Officinalis Leaf Extract, Glycerin, Alpha-Glucan Oligosaccharide, Coco-Glucoside, Glyceryl Oleate, Tocopherol, Hydrogenated Palm Glycerides Citrate, Citric Acid, Polyquaternium-10, Phenethyl Alcohol, Chlorphenesin, Sodium Benzoate, Potassium Sorbate.''',
    "Yves Rocher Volume Plumping Shampoo Sulfate Free": '''Aqua/water/eau • sodium cocoyl isethionate • sodium methyl cocoyl taurate • cocamidopropyl betaine • lauryl glucoside • chenopodium quinoa seed extract • fructooligosaccharides • inulin • sodium benzoate • parfum/fragrance • citric acid • panthenol • guar hydroxypropyltrimonium chloride • coco-glucoside • glyceryl oleate • potassium sorbate • sodium chloride • trisodium ethylenediamine disuccinate • tocopherol • lecithin • hydrogenated vegetable glycerides citrate''',
    "POLLYSH Basic": '''Aqua, Cocamidopropyl Betaine, Sodium Lauroyl Sarcosinate, Coco Glucoside, Sodium Coco Sulfate, Glycerin, Glyceryl Oleate, Bis-Diisopropanolamino-PG-Propyl Disiloxane/Bis-Vinyl Dimethicone Copolymer, Polyquaternium-7, Hydrolyzed Keratin, Chitosan Succinamide, Polyquaternium-10, PEG-120 Methyl Glucose Dioleate, Phenoxyethanol, Ethylhexylglycerin, Inulin, Panthenol, Parfum, Hydrolyzed Wheat Protein, Methicone, Carbocysteine, Hydroxypropyltrimonium Chloride.''',
    "AUSSIE Miracle Moist": '''Aqua, sodium lauryl sulfate, sodium laureth sulfate, cocamidopropyl betaine, glycol distearate, sodium citrate, cocamide mea, sodium xylenesulfonate, sodium chloride, parfum, sodium benzoate, citric acid, tetrasodium edta, guar hydroxypropyltrimonium chloride, sodium hydroxide, limonene, magnesium nitrate, aloe barbadensis leaf juice, macadamia ternifolia seed oil, ci 19140, methylchloroisothiazolinone, magnesium chloride, ci 17200, methylisothiazolinone. ''',
}

# строчка с потребностью - что именно хочет пользователь
features_or_problem = """
Я хочу решить проблему выпадения волос, так же шампунь должен быть с минимумом вредных компонентов
и подходить для частого использования. 
и чтобы после него на следующий день не было зуда.
"""

all_cosmetics = {}
