type_hair = "Волнистые, средней толщины, пористые, склонны к пушистости"
type_scalp = 'Нормальная'
features = 'Корни жирнеют быстро, длина и концы остаются сухими'

gender = 'женщина'
age = 32

info_about_cosmetics = {
    "AlterEgo Italy Scalpego Balancing": '''Aqua (Water), Ammonium Lauryl Sulfate, Sodium Myreth Sulfate, Sodium Cocoamphoacetate, Sodium Chloride, Parfum (Fragrance), Lactic Acid, Sodium Benzoate, Guar Hydroxypropyltrimonium Chloride, Sodium Hydroxide, Propanediol, Citric Acid, Tartaric Acid, Avena Sativa Leaf/Stalk Extract (Avena Sativa Oat Leaf/Stalk Extract), Gluconic Acid, Saccharomyces Ferment Lysate Filtrate, Almond/Borage/Linseed/Olive Acids/Glycerides, Glycerin, Potassium Sorbate, Panthenol, Tocopherol, Salvia Officinalis Extract, Nasturtium Officinale Extract, Rosmarinus Officinalis Leaf Extract (Rosmarinus Officinalis (Rosemary) Leaf Extract), Niacin, Biotin. ''',
    "AlterEgo Italy Curego Hydraday": '''Aqua (Water), Ammonium Lauryl Sulfate, Cocamidopropyl Betaine, Erythritol, Lactic Acid, Polysorbate 20, Parfum (Fragrance), Sodium Benzoate, Sodium Gluconate, Sodium Hydroxide, Propanediol, Guar Hydroxypropyltrimonium Chloride, Hexyl Cinnamal, Citric Acid, Geraniol, Linalool, Hydroxycitronellal, Tartaric Acid, Oryza Sativa (Rice) Extract, Gluconic Acid, Saccharomyces Ferment Lysate Filtrate, Sodium Chloride, Potassium Sorbate, Vitis Vinifera Seed Oil (Vitis Vinifera (Grape) Seed Oil), Glycerin, Sorbitol, Lecithin, Xanthan Gum.''',
    "Lador KERATIN LPP SHAMPOO": '''Water, Cocamidopropyl Betaine, Disodium Laureth Sulfosuccinate, Lauramine Oxide, TEA-Cocoyl Glutamate, Glycerin, Butylene Glycol, Lauramide DEA, PEG-120 Methyl Glucose Dioleate, Sodium Benzoate, PEG-7 Glyceryl Cocoate, PPG-3 Caprylyl Ether, Citric Acid, Polyquaternium-10, Betaine, Hydroxypropyl Chitosan, Hydrolyzed Wheat Protein, Hydrolyzed Corn Protein, Hydrolyzed Soy Protein, Hydrolyzed Silk, Hydroxyacetophenone, Sodium Hyaluronate, Trehalose, Dipropylene Glycol, Zein, Argania Spinosa Kernel Oil, Persea Gratissima (Avocado) Oil, Camellia Japonica Seed Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Fragrance''',
    "PAYOT Shampoing doux biome-friendly": '''Aqua (Water), Sodium Lauroyl Methyl Isethionate, Lauryl Glucoside, Cocamidopropyl Betaine, Sodium Methyl Cocoyl Taurate, Parfum (Fragrance), Pogostemon Cablin Leaf/Stem Extract, Salvia Officinalis Leaf Extract, Glycerin, Alpha-Glucan Oligosaccharide, Coco-Glucoside, Glyceryl Oleate, Tocopherol, Hydrogenated Palm Glycerides Citrate, Citric Acid, Polyquaternium-10, Phenethyl Alcohol, Chlorphenesin, Sodium Benzoate, Potassium Sorbate.''',
    "Yves Rocher Volume Plumping Shampoo Sulfate Free": '''Aqua/water/eau • sodium cocoyl isethionate • sodium methyl cocoyl taurate • cocamidopropyl betaine • lauryl glucoside • chenopodium quinoa seed extract • fructooligosaccharides • inulin • sodium benzoate • parfum/fragrance • citric acid • panthenol • guar hydroxypropyltrimonium chloride • coco-glucoside • glyceryl oleate • potassium sorbate • sodium chloride • trisodium ethylenediamine disuccinate • tocopherol • lecithin • hydrogenated vegetable glycerides citrate''',
    "POLLYSH Basic": '''Aqua, Cocamidopropyl Betaine, Sodium Lauroyl Sarcosinate, Coco Glucoside, Sodium Coco Sulfate, Glycerin, Glyceryl Oleate, Bis-Diisopropanolamino-PG-Propyl Disiloxane/Bis-Vinyl Dimethicone Copolymer, Polyquaternium-7, Hydrolyzed Keratin, Chitosan Succinamide, Polyquaternium-10, PEG-120 Methyl Glucose Dioleate, Phenoxyethanol, Ethylhexylglycerin, Inulin, Panthenol, Parfum, Hydrolyzed Wheat Protein, Methicone, Carbocysteine, Hydroxypropyltrimonium Chloride.''',
    "AUSSIE Miracle Moist": '''Aqua, sodium lauryl sulfate, sodium laureth sulfate, cocamidopropyl betaine, glycol distearate, sodium citrate, cocamide mea, sodium xylenesulfonate, sodium chloride, parfum, sodium benzoate, citric acid, tetrasodium edta, guar hydroxypropyltrimonium chloride, sodium hydroxide, limonene, magnesium nitrate, aloe barbadensis leaf juice, macadamia ternifolia seed oil, ci 19140, methylchloroisothiazolinone, magnesium chloride, ci 17200, methylisothiazolinone. ''',
}

# строчка с потребностью - что именно хочет пользователь
features_or_problem = """
Я хочу решить проблему выпадения волос, так же шампунь должен быть с минимумом вредных компонентов
и подходить для частого использования. и чтобы после него на следующий день не было зуда.
"""
